DEFAULT_CONFIG = {
    "app": {
        "name": "PV2Hash",
        "host": "0.0.0.0",
        "port": 8000,
        "refresh_seconds": 5,
        "theme": "dark",
    },
    "system": {
        "instance_name": "PV2Hash Node",
        "log_level": "INFO",
        "check_updates": True,
        "auto_update_enabled": False,
    },
    "source": {
        "type": "simulator",
        "name": "Simulator Source",
        "enabled": True,
        "settings": {
            "multicast_ip": "239.12.255.254",
            "bind_port": 9522,
            "interface_ip": "0.0.0.0",
            "packet_timeout_seconds": 1.0,
            "stale_after_seconds": 8.0,
            "offline_after_seconds": 30.0,
            "device_ip": "",
            "simulator_import_power_w": 1000.0,
            "simulator_export_power_w": 10000.0,
            "simulator_ramp_rate_w_per_minute": 600.0,
        },
    },
    "miners": [
        {
            "id": "m1",
            "name": "Miner 1",
            "host": "192.168.11.101",
            "driver": "simulator",
            "enabled": True,
            "priority": 10,
            "serial_number": "SIM-M1",
            "model": "Simulator",
            "firmware_version": "sim-0.1",
            "settings": {
                "port": 4028,
            },
            "profiles": {
                "p1": {"power_w": 900},
                "p2": {"power_w": 1800},
                "p3": {"power_w": 3000},
                "p4": {"power_w": 4200},
            },
            "min_regulated_profile": "off",
        },
        {
            "id": "m2",
            "name": "Miner 2",
            "host": "192.168.11.102",
            "driver": "simulator",
            "enabled": True,
            "priority": 20,
            "serial_number": "SIM-M2",
            "model": "Simulator",
            "firmware_version": "sim-0.1",
            "settings": {
                "port": 4028,
            },
            "profiles": {
                "p1": {"power_w": 900},
                "p2": {"power_w": 1800},
                "p3": {"power_w": 3000},
                "p4": {"power_w": 4200},
            },
            "min_regulated_profile": "off",
        },
    ],
    "control": {
        "policy_mode": "coarse",
        "distribution_mode": "equal",
        "min_switch_interval_seconds": 60,
        "cooldown_seconds": 15,
        "switch_hysteresis_w": 100,
        "max_import_w": 200,
        "import_hold_seconds": 15,
        "source_loss": {
            "stale": {
                "mode": "hold_current",
                "fallback_profile": "p1",
                "hold_seconds": 0,
            },
            "offline": {
                "mode": "off_all",
                "fallback_profile": "p1",
                "hold_seconds": 0,
            },
        },
    },
}