DEFAULT_CONFIG = {
    "app": {
        "name": "PV2Hash",
        "host": "0.0.0.0",
        "port": 8000,
        "refresh_seconds": 5,
        "theme": "dark",
    },
    "system": {
        "instance_name": "PV2Hash Node",
        "log_level": "INFO",
        "check_updates": True,
        "update_repo": "phlupp/pv2hash",
    },
    "datalogger": {
        "enabled": True,
        "interval_seconds": 10,
        "retention_days": 7,
    },
    "source": {
        "type": "simulator",
        "name": "Simulator Source",
        "enabled": True,
        "settings": {
            "multicast_ip": "239.12.255.254",
            "bind_port": 9522,
            "interface_ip": "0.0.0.0",
            "packet_timeout_seconds": 1.0,
            "stale_after_seconds": 8.0,
            "offline_after_seconds": 30.0,
            "device_serial_number": "",
            "debug_dump_obis": False,
            "simulator_import_power_w": 1000.0,
            "simulator_export_power_w": 10000.0,
            "simulator_ramp_rate_w_per_minute": 600.0,
        },
    },
    "battery": {
        "type": "none",
        "name": "Batterie",
        "enabled": False,
        "charge_active_threshold_w": 100.0,
        "discharge_active_threshold_w": 100.0,
        "settings": {
            "host": "",
            "port": 502,
            "unit_id": 1,
            "poll_interval_ms": 1000,
            "request_timeout_seconds": 1.0,
            "soc": {
                "register_type": "holding",
                "address": None,
                "value_type": "uint16",
                "endian": "big_endian",
                "factor": 1.0,
            },
            "charge_power": {
                "register_type": "holding",
                "address": None,
                "value_type": "int16",
                "endian": "big_endian",
                "factor": 1.0,
            },
            "discharge_power": {
                "register_type": "holding",
                "address": None,
                "value_type": "int16",
                "endian": "big_endian",
                "factor": 1.0,
            },
        },
    },
    "sockets": [],
    "miners": [
        {
            "id": "m1",
            "name": "Miner 1",
            "host": "192.168.11.101",
            "driver": "simulator",
            "monitor_enabled": True,
            "control_enabled": True,
            "priority": 10,
            "serial_number": "SIM-M1",
            "model": "Simulator",
            "firmware_version": "sim-0.1",
            "settings": {
                "port": 4028,
            },
            "profiles": {
                "p1": {"power_w": 900},
                "p2": {"power_w": 1800},
                "p3": {"power_w": 3000},
                "p4": {"power_w": 4200},
            },
            "min_regulated_profile": "off",
            "use_battery_when_charging": False,
            "battery_charge_soc_min": 95.0,
            "battery_charge_profile": "p1",
            "use_battery_when_discharging": False,
            "battery_discharge_soc_min": 80.0,
            "battery_discharge_profile": "p1",
        },
    ],
    "control": {
        "policy_mode": "coarse",
        "distribution_mode": "equal",
        "min_switch_interval_seconds": 300,
        "cooldown_seconds": 15,
        "switch_hysteresis_w": 100,
        "max_import_w": 100,
        "import_hold_seconds": 15,
        "source_loss": {
            "stale": {
                "mode": "hold_current",
                "fallback_profile": "p1",
                "hold_seconds": 0,
            },
            "offline": {
                "mode": "off_all",
                "fallback_profile": "p1",
                "hold_seconds": 0,
            },
        },
    },
}
